apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "helm.fullname" . }}-webapp"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["locust"]
            {{- with .Values.webapp }}
            args:
              - "--headless"
              - "--host"
              - {{ .host | quote }}
              - "--locustfile"
              - {{ .file | quote }}
              - "--users"
              - {{ .users | quote }}
              - "--spawn-rate"
              - {{ .spawnRate | quote }}
              - "--run-time"
              - {{ .runTime | quote }}
              - "--csv"
              - {{ .csvFilename | quote }}
            {{- end }}
            volumeMounts:
            - mountPath: /statistics
              name: storage
          volumes:
          - name: storage
            persistentVolumeClaim:
              claimName: locust-webapp-pvc
          restartPolicy: Never