---
- name: Ensure mygithub repo exists
  kubernetes.core.helm_repository:
    name: mygithub
    repo_url: https://filbary.github.io/test

- name: Ensure locust is deployed
  kubernetes.core.helm:
    name: locust
    chart_ref: mygithub/locust
    namespace: "{{ namespace }}"
    update_repo_cache: yes
    kubeconfig: "{{ kubeconfig }}"
    state: present
    history_max: 3
    wait: false
    values:
      fullnameOverride: locust
      webapp:
        host: http://webapp:8080
        file: webapp.py
        users: 100
        spawnRate: 10
        runTime: 15
      config: |
        locustfile = ./locustfiles
        class-picker = true