replicaCount: 1

image:
  repository: filbary/testlocust
  pullPolicy: Always
  tag: "latest"

# config: |
#   locustfile = ./locustfile.py
#   headless = true
#   host = http://testgo:8080
#   users = 10
#   spawn-rate = 10
#   run-time = 5s
#   csv = example

config: |
  locustfile = ./locustfiles
  class-picker = true

webapp:
  host: http://webapp:8080
  file: "./locustfiles/webapp.py"
  users: 100
  spawnRate: 10
  runTime: 360
  csvFilename: "/statistics/"

serving:
  host: http://serving:8501
  file: "./locustfiles/serving.py"
  users: 100
  spawnRate: 10
  runTime: 360
  csvFilename: "/statistics/"

imagePullSecrets: []
nameOverride: "locust"
fullnameOverride: "locust"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8089
  nodePort: 31700

resources: {}
  # requests:
  #   cpu: 1000m
  #   memory: 6Gi

volumes:
- name: config
  configMap:
    name: locust

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: config
  mountPath: "/etc/mylocust"
  readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
