replicaCount: 1

image:
  repository: filbary/testserving
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: "serving"
fullnameOverride: "serving"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: NodePort
  port: 8080
  nodePort: 31698

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
