apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
  {{- end }}