---
- name: Ensure mygithub repo exists
  kubernetes.core.helm_repository:
    name: mygithub
    repo_url: https://filbary.github.io/test

- name: Ensure webapp is deployed
  kubernetes.core.helm:
    name: webapp
    chart_ref: mygithub/webapp
    namespace: "{{ namespace }}"
    update_repo_cache: yes
    kubeconfig: "{{ kubeconfig }}"
    state: present
    history_max: 3
    wait: false
    values:
      fullnameOverride: webapp