---
- hosts: 192.168.0.205
  gather_facts: false
  become: false
  tasks:
  - name: Find directory containing 'serving'
    find:
      paths: "/data"
      patterns: '*serving*'
      recurse: yes
      file_type: directory
    register: serving_dirs

  - name: Copy serving directory contents to local machine
    synchronize:
      src: "{{ item.path }}/"
      dest: "results/serving/"
      mode: pull
    loop: "{{ serving_dirs.files }}"
    when: serving_dirs.matched > 0
  
  - name: Find directory containing 'webapp'
    find:
      paths: "/data"
      patterns: '*webapp*'
      recurse: yes
      file_type: directory
    register: webapp_dirs

  - name: Copy webapp directory contents to local machine
    synchronize:
      src: "{{ item.path }}/"
      dest: "results/webapp/"
      mode: pull
    loop: "{{ webapp_dirs.files }}"
    when: webapp_dirs.matched > 0

