---
- hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - include_role:
        name: namespaces
    - include_role:
        name: webapp
    - include_role:
        name: locust


    # - include_role:
    #     name: reset