---
- hosts: localhost
  gather_facts: false
  become: false
  tasks:
    # - include_role:
    #     name: namespaces
    - include_role:
        name: volumes
    # - include_role:
    #     name: reset

    # - include_role:
    #     name: webapp
    # - include_role:
    #     name: serving
    # - include_role:
    #     name: locust