---
- name: Create namespaces
  kubernetes.core.k8s:
    kubeconfig: "{{kubeconfig}}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ns.name }}"
        labels:
          name: "{{ ns.name }}"
  with_items: "{{ namespaces.names }}"
  loop_control:
    loop_var: ns